db:
  name: cloud_storage
  setting: ?useSSL=false&useUnicode=yes&characterEncoding=UFT-8&allowPublicKeyRetrieval=true&amp;serverTimezone=UTC
#  host: 192.168.110.6
  port: 5432
#  password: 12345678

app:
  port: 8080
  host: 127.0.0.1

spring:
  datasource:
    url: jdbc:postgresql://${db.host:127.0.0.1}:${db.port:5432}/${db.name:postgres}${db.setting:}
    username: postgres
    password: ${db.password:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: warn
    ru:
      cloud:
        storage:
          backendjavacloudstorage:
            BackendJavaCloudStorageApplication: info
server:
  port: ${app.port:8080}
  address: ${app.host:127.0.0.1}
